# Generated by Django 4.0.1 on 2022-01-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Comment',
        ),
    ]
